"""
Per-zone bootstrap CI for the W2 minus W1 MAPE shift.

For each (zone, model), we resample the 7 forecast days within each
window independently (with replacement), compute the per-window mean
MAPE, take the difference, and read 2.5/97.5-percentile bounds. The
CI tells us whether each zone's drift shift is meaningfully nonzero.

This strengthens §4's per-zone breakdown by showing that the
geographic concentration is statistically robust, not just a point
estimate that could plausibly be zero.

Inputs : report/arxiv/data/multi_window_results.json
Outputs: report/arxiv/data/per_zone_diff_ci.json
         report/arxiv/_tbl_per_zone_diff.tex   (LaTeX table input)
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
INPUT = ROOT / "report" / "arxiv" / "data" / "multi_window_results.json"
OUT_DATA = ROOT / "report" / "arxiv" / "data" / "per_zone_diff_ci.json"
OUT_TBL = ROOT / "report" / "arxiv" / "_tbl_per_zone_diff.tex"

ZONES = ["ME", "NH", "VT", "CT", "RI", "SEMA", "WCMA", "NEMA_BOST"]
ZONE_LABEL = {z: z.replace("_", "\\_") for z in ZONES}
MODELS = ["baseline", "chronos", "ensemble"]


def _per_pair_mape(forecasts: list, model: str) -> np.ndarray:
    """Return (n_forecasts, 8) per-day per-zone MAPE in percent."""
    truths = np.stack([np.array(f["truth_24h"]) for f in forecasts], axis=0)
    preds = np.stack([np.array(f["predictions"][model]) for f in forecasts], axis=0)
    abs_pct = np.abs(preds - truths) / np.abs(truths)
    return 100.0 * abs_pct.mean(axis=1)   # mean over hours


def main() -> None:
    multi = json.loads(INPUT.read_text())
    windows = {w["label"]: w for w in multi["windows"]}
    rng = np.random.default_rng(42)
    n_resamples = 5000

    out = {"schema_version": "v1.6-per-zone-diff-ci",
            "n_resamples": n_resamples,
            "ci_level": 0.95,
            "models": {}}

    for m in MODELS:
        per_zone = {}
        w1 = _per_pair_mape(windows["W1"]["forecasts"], m)   # (7, 8)
        w2 = _per_pair_mape(windows["W2"]["forecasts"], m)   # (7, 8)
        n_w1, _ = w1.shape
        n_w2, _ = w2.shape
        for j, z in enumerate(ZONES):
            w1_col = w1[:, j]
            w2_col = w2[:, j]
            # bootstrap 7 days each window
            boot_w1 = rng.choice(w1_col, size=(n_resamples, n_w1), replace=True).mean(axis=1)
            boot_w2 = rng.choice(w2_col, size=(n_resamples, n_w2), replace=True).mean(axis=1)
            diff_boot = boot_w2 - boot_w1
            point = float(w2_col.mean() - w1_col.mean())
            ci_lo = float(np.quantile(diff_boot, 0.025))
            ci_hi = float(np.quantile(diff_boot, 0.975))
            per_zone[z] = {
                "w1_mape_pct": float(w1_col.mean()),
                "w2_mape_pct": float(w2_col.mean()),
                "diff_pp": point,
                "ci_low_pp": ci_lo,
                "ci_high_pp": ci_hi,
                "ci_excludes_zero": ci_lo > 0 or ci_hi < 0,
            }
        out["models"][m] = per_zone

    OUT_DATA.write_text(json.dumps(out, indent=2))
    print(f"Wrote {OUT_DATA}")
    print()
    print("Per-zone W2-W1 MAPE shift, baseline model:")
    for z, r in out["models"]["baseline"].items():
        excl = "✓" if r["ci_excludes_zero"] else " "
        print(f"  {z:11s}: {r['diff_pp']:+6.2f}pp "
               f"[{r['ci_low_pp']:+6.2f}, {r['ci_high_pp']:+6.2f}] {excl}")

    # Render as a LaTeX-input table (Appendix F).
    lines = [
        "% Auto-generated by render_per_zone_diff_ci.py — do not hand-edit",
        "\\begin{tabular}{@{}lrrr@{}}",
        "\\toprule",
        "Zone & Baseline $\\Delta$ MAPE [95\\%~CI] & Chronos $\\Delta$ MAPE [95\\%~CI] & Ensemble $\\Delta$ MAPE [95\\%~CI] \\\\",
        "\\midrule",
    ]
    for z in ZONES:
        cells = []
        for m in MODELS:
            r = out["models"][m][z]
            sig = "$^*$" if r["ci_excludes_zero"] else ""
            cells.append(f"{r['diff_pp']:+.1f}{sig} [{r['ci_low_pp']:+.1f}, {r['ci_high_pp']:+.1f}]")
        lines.append(f"{ZONE_LABEL[z]} & " + " & ".join(cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "% $^*$ marks zones whose 95\\% CI excludes zero.",
    ]
    OUT_TBL.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TBL}")


if __name__ == "__main__":
    main()
